all: test1 test2 test3 test4 test5 test6 test7 test8 test9

test1:
	gcc -Wall -o test_obscenity_filter.o test_obscenity_filter.c

test2:
	 gcc -Wall -o test_secure_vector.o test_secure_vector.c

test3:
	 gcc -Wall -o get_proc_vector.o get_proc_vector.c

test4:
	 gcc -Wall -o sleep_test_obscenity_filter.o sleep_test_obscenity_filter.c
	
test5:
	 gcc -Wall -o sleep_test_secure_vector.o sleep_test_secure_vector.c
	
test6:
	 gcc -Wall -o test_change_vector.o test_change_vector.c

test7:
	gcc -Wall -o test_clone_flag.o test_clone.c

test8:
	gcc -Wall -o test_clone2.o test_clone2.c

test9:
	gcc -Wall -o set_default_vector.o set_default_vector.c
